# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         tidyview
version:      1.11
version_from: lib/TidyView/VERSION.pm
installdirs:  site
requires:
    Log::Log4perl:                 1.0
    Perl::Tidy:                    0
    Tk:                            800.025
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
